### ISSUE TITLE
简繁搜索

### ISSUE THREAD

**Issue by lwy92** [hankcs/hanlp-lucene-plugin#20]
作者，您好  插件怎么能实现我搜索简体字自动转为繁体和简体去搜索   搜繁体字也能自动转为繁体和简体去搜索  谢谢了

**Comment by hankcs** [comment]
暂不支持。

**Comment by lwy92** [comment]
能加一个吗  感觉对你来说是很容易的事啦  谢谢了啊

**Comment by lwy92** [comment]
或者能告诉我大致怎么加  我自己加也行

**Comment by lwy92** [comment]
帮忙下拉  大哥

**Comment by hankcs** [comment]
你为什么不用lucene的同义词呢？
