### ISSUE TITLE
solr copyfield index 出错

### ISSUE THREAD

**Issue by quicksandznzn** [hankcs/hanlp-lucene-plugin#32]
报错内容如下：

Caused by: java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=3,endOffset=5,lastStartOffset=4 for field 'q'

schema如下
![image](https://user-images.githubusercontent.com/23514918/35952665-10be1f82-0cbc-11e8-9fe7-edcd49e54db3.png)

**Comment by quicksandznzn** [comment]
<fieldType name="text_hanlp" class="solr.TextField">
      <analyzer type="index">
          <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="true" stopWordDictionaryPath="/usr/local/solr-7.1.0/server/solr-webapp/webapp/WEB-INF/classes/stopwords/stopwords.txt"/>
           <filter class="solr.LowerCaseFilterFactory" /> 
     		<charFilter class="solr.HTMLStripCharFilterFactory" /> 
      </analyzer>
      <analyzer type="query">
          
          <tokenizer class="com.hankcs.lucene.HanLPTokenizerFactory" enableIndexMode="false" stopWordDictionaryPath="/usr/local/solr-7.1.0/server/solr-webapp/webapp/WEB-INF/classes/stopwords/stopwords.txt"/>
           <filter class="solr.LowerCaseFilterFactory" /> 
     		<charFilter class="solr.HTMLStripCharFilterFactory" /> 
      </analyzer>
  </fieldType>

**Comment by hankcs** [comment]
https://github.com/hankcs/hanlp-lucene-plugin/issues/27
https://github.com/hankcs/hanlp-lucene-plugin/pull/30
