### ISSUE TITLE
java: org.apache.lucene.util.RamUsageEstimator 中的 NUM_BYTES_CHAR 已过时

### ISSUE THREAD

**Issue by AnyListen** [hankcs/hanlp-lucene-plugin#36]
`PorterStemmer.java` 中 
`import static org.apache.lucene.util.RamUsageEstimator.NUM_BYTES_CHAR;` 
已经不建议使用了，可用使用 `Character.BYTES` 替换

**Comment by hankcs** [comment]
欢迎pr

**Comment by AnyListen** [comment]
仔细看了下，只有JDK1.8才开始支持 `Character.BYTES`
