### ISSUE TITLE
solr使用enableTraditionalChineseMode时，导入数据会出现报错

### ISSUE THREAD

**Issue by jiuxs33** [hankcs/hanlp-lucene-plugin#44]
possible analysis error: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=0,endOffset=5,lastStartOffset=2 for field 'search_field'

**Comment by hankcs** [comment]
已经修复 https://github.com/hankcs/HanLP/commit/455f59335fa4b12eeae72ff015c0fbb02f5b1e0c ，请升级最新版。
