### ISSUE TITLE
如果词语中含有“0.01元”，则会将“.”作为句尾导致分词结果为[0] [.] [01] [元]，不知道这是否算作bug。

### ISSUE THREAD

**Issue by 468120308** [hankcs/hanlp-lucene-plugin#48]
![image](https://user-images.githubusercontent.com/29749241/57967288-9a72a680-798f-11e9-8b10-14b6ff3ece30.png)

**Comment by hankcs** [comment]
你好，已经在 https://github.com/hankcs/hanlp-lucene-plugin/commit/c0dfdb1de71d9f322f1f131879dbd91d89c562ce 中修复。
